### DISCUSSION TITLE
Ktra and docker compose

### DISCUSSION THREAD

**Discussion by Geobert** [moriturus/ktra#10] [Q&A] [answered]
Hi,

So as you know, I'm trying to setup ktra in our workplace and I've chosen the Docker way. Our Docker guy told me I need to setup a compose file so we'll have the persistent binding volume to store ktra's data.

Currently, the file looks like this:
```yml
version: "3.9"
services:
  ktra: 
    image: ghcr.io/moriturus/ktra:0.5.0
    configs:
      - source: ktra_cfg
        target: /ktra.toml
    volumes:
      - type: bind
        source: ./drive/crates
        target: /crates
      - type: bind
        source: ./drive/crates_io_caches
        target: /crates_io_caches
      - type: bind
        source: ./drive/db
        target: /db
      - type: bind
        source: ./drive/index
        target: /index

configs:
  ktra_cfg:
    file: ./ktra.toml
```

in the ktra.toml, there's only `remote_url`, `https_username`, and the password, `branch` is `master` in our case.

when running `docker-compose up`:
```
ktra_1  | Error: git error: could not find repository from 'index'; class=Repository (6); code=NotFound (-3)
```

my `index` folder is indeed empty, but I was expecting Ktra to fill it itself using `remote_url`

What am I doing wrong here?

Another thing is that I've seen that if a wrong config file path is given, you just use a default configuration. I think it would be better to reject the execution with a proper error message :)

**Comment by moriturus** [comment, marked as answer]
Hello @Geobert .

First of all, `ktra` checks that the local index repository directory *does exist or not*.  
If the directory exists `ktra` treats it as a cloned-repository then try to pull and merge the latest index from the remote repository. Otherwise `ktra` is going to create a new directory.  
So **you should not create an empty directory** and the error message you have shown is caused by it.

Secondly, and as far as I know, `configs` settings in the `docker-compose.yml` won't be working unless you use [the docker swarm mode](https://docs.docker.com/engine/swarm/).  
I think the most simple way to mount your `ktra.toml` file to a container is using `volumes` feature.

Based on the above, I've tried writing a `docker-compose.yml` file:

```yaml
version: "3.9"
services:
  ktra: 
    image: ghcr.io/moriturus/ktra:0.5.0
    environment:
      - RUST_LOG=ktra,warp=debug
    command:
      - "--dl-dir-path=/data/crates"
      - "--cache-dir-path=/data/crates_io_caches"
      - "--db-dir-path=/data/db"
      - "--local-path=/data/index"
    volumes:
      - ./ktra.toml:/ktra.toml
      - type: bind
        source: ./drive
        target: /data
```

I can run the container without error messages using this settings.  

I really appreciate your practical using of `ktra`!  
Please tell me if there is any progress😉.

**Reply by Geobert** [reply]
Thank you for your answer! I'll try that tomorrow (I'm in the UK and the work day's over :) ) Of course I'll keep you posted!

**Reply by Geobert** [reply]
I'm progressing!

We had to switch to SSH protocol for git as the repo's SSL cert is under a self signed root cert and I don't know how to add an anchor in your image (I'm not a Docker pro)

Anyway, I'm using ssh_* configuration keys to add the user, private and public keys. But here is what I get:
```
Starting ktra_docker_ktra_1 ... done
Attaching to ktra_docker_ktra_1
ktra_1  | Feb 05 10:06:38.295  INFO run_server: ktra: crates directory: "/data/crates"
ktra_1  | Feb 05 10:06:38.298  INFO run_server:new: ktra::db_manager::sled_db_manager: create and/or open 
database: "/data/db"
ktra_1  | Feb 05 10:06:38.322  INFO run_server:new:clone_or_open_repository: ktra::index_manager: try to clone index repository into "/data/index"
ktra_1  | Error: git error: failed to mmap. Could not write data: Permission denied; class=Os (2)
ktra_docker_ktra_1 exited with code 1
```

the other directory are created (crates, db and the mirroring dir) but it seems that the cloning can't write for some reason :-/

excerpt of the config:
```yml
[index_config]
# remote_url and ssh_* config keys skipped
local_path = "/data/index"

[crate_files_config]
dl_dir_path = "/data/crates"
cache_dir_path = "/data/crates_io_caches"

[db_config]
db_dir_path = "/data/db"
```

**Reply by moriturus** [reply]
Hm, It seems a problem with your git remote server's permission.

Please confirm that the container mounts ssh public/private keys to its internal file system in your `docker-compose.yml` like this:

```yaml
    volumes:
      - ~/.ssh:/ssh
      - ./ktra.toml:/ktra.toml
      - type: bind
        source: ./drive
        target: /data
```

And if you mounts your ssh keys to `/ssh`, the `ktra` configs should be like this:

```toml
ssh_username = "moriturus"
ssh_pubkey_path = "/ssh/moriturus_ed25519.pub"
ssh_privkey_path = "/ssh/moriturus_ed25519"
```
