### ISSUE TITLE
Ktra server commits empty files

### ISSUE THREAD

**Issue by jean-airoldie** [moriturus/ktra#20]
Trying to get this to work with the following configuration:

```toml
[index_config]
remote_url = "https://github.com/******************.git"
https_username = "*********************************"
https_password = "**********************************"
branch = "master"
```

... but when I publish a crate the ktra server publishes empty files in the git index, instead of metadata files. This results in the package tarball verification failing when trying to pull the crate.

**Comment by jean-airoldie** [comment]
Specifically, it seems like the local index is working properly but not the remote index.

**Comment by jean-airoldie** [comment]
Somehow it seems that the actual content of the files does not get committed. I wonder if this has to do with some working directory stuff.

**Comment by jean-airoldie** [comment]
Alright I think i found it. Seems like the files were committed before they were even flushed to disk. I'll submit a PR.

**Comment by jbeaurivage** [comment]
@jean-airoldie, it seems like my ktra install is still committing empty files, even when using a branch with #21 merged. Here is what happens:

* Index is hosted on gitlab
* running `cargo publish --registry my-registry` works just fine. The crate is downloaded, and the metadata is committed to the local index repo.
* The metadata file pushed to the remote index is empty, even though the metadata is very much in the local index repo.
* Running `git diff origin master` from the local index repo says there aren't any changes.
* Adding a change manually to the local metadata file (say, adding whitespace or something) make the changes "appear" in the diff. The file can now be pushed and will appear non-empty in the remote index.

Any idea what could cause this? The branch I'm using to test this is [here](https://github.com/jbeaurivage/ktra/tree/develop).

**Comment by jean-airoldie** [comment]
I can't say I have an idea since it's been a while, but I can tell you what my config is at least.

I using this fork https://github.com/jean-airoldie/ktra. I run the ktra server via systemd on a 3rd party VPS and the index hosted privately on github.

## ktra server
```service
# /etc/systemd/system/ktra.service
[Unit]
Description=Ktra server

[Service]
ExecStart=/root/.cargo/bin/ktra # path to the compiled binary
WorkingDirectory=/etc/ktra/

[Install]
WantedBy=multi-user.target
```

```toml
# /etc/ktra/config.toml
[index_config]
remote_url = "https://github.com/jean-airoldie/ktra-index.git"
https_username = "*********************"
https_password = "**************************************************"
branch = "master" # make sure this is the branch that match your fork
git_email = "*********************************"
git_name = "ktra-server"
```

## github index
```json
{"dl":"http://<VSP_IP_HERE>:8000/dl","api":"http://<VPS_IP_HERE>:8000"}
```

## local config
```toml
# Cargo.toml
publish = ["ktra"] # add this line to your cargo.toml to not accidentally publish on crates.io
```

```toml
# .cargo/config.toml
[net]
git-fetch-with-cli = true

[registries]
ktra = { index = "https://github.com/jean-airoldie/ktra-index.git" }
```
